import ReduxProvider from '@/store/Provider';
 import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Header } from './Layout/Header/Header';
import { Footer } from './Layout/Footer/Footer';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Sky Trader',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ReduxProvider>
					<>
						<Header />
					</>
					{children}
					<>
						<Footer />
					</>
				</ReduxProvider>
			</body>
		</html>
	);
}
